apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-plugin-catalog-backend-module-github
  namespace: rhdh
  title: "Catalog Backend Module GitHub"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/backstage/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/backstage/tree/master/plugins/catalog-backend-module-github
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/master/plugins/catalog-backend-module-github
  tags:
    - software-catalog
spec:
  packageName: "@backstage/plugin-catalog-backend-module-github"
  # Tag: bs_1.54.6__0.13.5, Build date: 2026-05-21T21:07:49Z
  dynamicArtifact: "oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-plugin-catalog-backend-module-github@sha256:df50f7a2013a88dea71d37b8240c60651dc9f2e9b3af2eee6ea8f961e317f2f9"
  version: 0.13.5
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.54.6
  author: Red Hat
  support: generally-available
  lifecycle: active
  partOf:
    - backstage-plugin-catalog-backend-module-github
  appConfigExamples:
    - title: Default configuration
      content:
        catalog:
          providers:
            github:
              providerId:
                organization: ${GITHUB_ORG}
