apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-plugin-user-settings-backend
  namespace: rhdh
  title: 'User Settings Backend'
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/backstage/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/backstage/tree/v1.49.4/plugins/user-settings-backend
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/v1.49.4/plugins/user-settings-backend
  tags: []
spec:
  packageName: '@backstage/plugin-user-settings-backend'
  dynamicArtifact: ./dynamic-plugins/dist/backstage-plugin-user-settings-backend-dynamic
  version: 0.4.1
  backstage:
    role: backend-plugin
    supportedVersions: 1.49.4
  author: Red Hat
  support: generally-available
  lifecycle: active
  partOf:
    - user-settings
  appConfigNotRequired: true
  appConfigExamples: []
