#!/usr/bin/env bash
#
# Merge per-test Istanbul coverage JSONs, generate lcov, and upload to Codecov.
# Coverage is attributed to this overlay repo's commit, flagged per workspace
# (see upload-coverage.sh for the attribution model).
#
# Usage:
#   ./scripts/report-coverage.sh <workspace> [workspace...]
#
# Example:
#   E2E_COLLECT_COVERAGE=true ./run-e2e.sh -w tech-radar
#   ./scripts/report-coverage.sh tech-radar
#
# The script:
#   1. Merges per-test coverage JSONs (written by the _coverageCollector fixture)
#      into a single coverage-final.json using nyc merge
#   2. Generates lcov and text-summary reports via nyc report
#   3. Uploads lcov to Codecov flagged per workspace (e2e-<workspace>)
#
# Required environment:
#   CODECOV_TOKEN  - Codecov upload token for this repo's project

set -euo pipefail

if [[ $# -eq 0 ]]; then
  echo "Usage: $0 <workspace> [workspace...]" >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
WORKSPACES=("$@")

COVERAGE_JSON_DIR="node_modules/.cache/e2e-test-results/coverage"

if ! compgen -G "$REPO_ROOT/$COVERAGE_JSON_DIR/*.json" >/dev/null 2>&1; then
  echo "[INFO] No coverage data found (no instrumented plugins loaded?)"
  exit 0
fi

echo ""
echo "[INFO] Merging coverage data with nyc..."
mkdir -p "$REPO_ROOT/.nyc_output"
npx nyc@18.0.0 merge "$REPO_ROOT/$COVERAGE_JSON_DIR" "$REPO_ROOT/.nyc_output/out.json"

# Remap bundle coverage back to source and emit lcov.
#
# Plugins are instrumented post-build (on the `dist/` and `dist-scalprum/`
# bundles), so the collected coverage is keyed by bundle paths that only existed
# in the publish job's temp dir. `nyc report` cannot resolve those paths here and
# would report 0/0. remap-coverage.cjs applies the source maps nyc embedded
# (`--source-map`) to map coverage onto the original source files and write lcov.
#
# The istanbul libraries are installed into a throwaway prefix so they never land
# in the repo or a workspace's node_modules. Keep these pins in sync with the
# istanbul API that remap-coverage.cjs relies on.
echo "[INFO] Remapping bundle coverage to source and generating lcov..."
# Single-workspace runs (the only ones that upload) remap against the
# committed anchor files (workspaces/<ws>/coverage-anchors/, generated by
# generate-coverage-anchors.sh) so the lcov paths exist in this repo's git
# tree — Codecov drops report paths it can't resolve against the tree.
REMAP_WORKSPACE=""
[[ ${#WORKSPACES[@]} -eq 1 ]] && REMAP_WORKSPACE="${WORKSPACES[0]}"
REMAP_DEPS_DIR=$(mktemp -d)
if ! { npm install --prefix "$REMAP_DEPS_DIR" --no-save --no-audit --no-fund --loglevel=error \
    istanbul-lib-coverage@3.2.2 \
    istanbul-lib-source-maps@5.0.6 \
    istanbul-lib-report@3.0.1 \
    istanbul-reports@3.2.0 \
  && (cd "$REPO_ROOT" && NODE_PATH="$REMAP_DEPS_DIR/node_modules" \
      node "$SCRIPT_DIR/remap-coverage.cjs" "$REPO_ROOT/.nyc_output/out.json" coverage "$REMAP_WORKSPACE"); }; then
  echo "[WARN] Coverage remap/report failed (non-fatal); skipping upload" >&2
  rm -rf "$REMAP_DEPS_DIR"
  exit 0
fi
rm -rf "$REMAP_DEPS_DIR"

# Known gap: this guard means the nightly job (which runs ALL workspaces in
# one invocation) never uploads — so no commit on main ever receives coverage
# and the per-flag trend on the Codecov dashboard can't form; only PR-head
# commits get data. Multi-workspace runs invoke the remap once with no
# workspace argument, and a webpack remote alone doesn't identify which
# workspace it came from — lifting the guard needs a remote->workspace
# mapping (e.g. from each workspace's coverage-anchors/ set) so per-workspace
# lcov files can be emitted and uploaded under their own flags. Planned as a
# follow-up to the overlay attribution model (PR #2580).
if [[ ${#WORKSPACES[@]} -gt 1 ]]; then
  echo "[WARN] Multi-workspace coverage upload is not supported." >&2
  echo "[WARN] Coverage is merged across workspaces but uploaded with per-workspace flags." >&2
  echo "[WARN] This produces misleading coverage percentages in Codecov." >&2
  echo "[WARN] Skipping upload. Run report-coverage.sh once per workspace to upload." >&2
else
  echo "[INFO] Uploading E2E coverage to Codecov..."
  for ws in "${WORKSPACES[@]}"; do
    if [[ -d "$REPO_ROOT/workspaces/$ws" ]]; then
      "$SCRIPT_DIR/upload-coverage.sh" "$ws" || \
        echo "[WARN] Coverage upload failed for $ws (non-fatal)"
    else
      echo "[WARN] Workspace '$ws' not found under workspaces/ — skipping upload" >&2
    fi
  done
fi
