name: Publish RHDH Release Dynamic Plugin Images
on:
  push:
    branches:
      - 'release-**'
      - 'main'

jobs:
  export:
    uses: redhat-developer/rhdh-plugin-export-overlays/.github/workflows/publish-release-branch-workspace-plugins.yaml@main
    permissions:
      contents: write
      attestations: write
      packages: write
      id-token: write
