name: Run Plugin Integration Tests

on:
  workflow_call:
    inputs:
      workspace-path:
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    permissions:
      contents: read
      packages: read
    steps:
      - name: Download integration test artifacts
        uses: actions/download-artifact@v4
        with:
          name: integration-test-artifacts
          path: ./artifacts

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Start RHDH with Layered Test Config
        env:
          WORKSPACE_PATH: ${{ inputs.workspace-path }}
        run: |
          set -euo pipefail
          ls -la ./artifacts/ || true
          
          if [ ! -f "./artifacts/dynamic-plugins.test.yaml" ]; then
            echo "Error: dynamic-plugins.test.yaml not found in artifacts"
            exit 1
          fi

          echo "dynamic-plugins.test.yaml contents:"
          sed -n '1,40p' ./artifacts/dynamic-plugins.test.yaml || true
          
          # Build Docker run command with conditional volume mounts
          DOCKER_CMD="docker run -d --name rhdh -p 7007:7007"
          if [ -f "./artifacts/app-config.yaml" ]; then
            DOCKER_CMD="$DOCKER_CMD -v $(pwd)/artifacts/app-config.yaml:/opt/app-root/src/app-config.yaml"
          fi
          if [ -f "./artifacts/app-config.test.yaml" ]; then
            DOCKER_CMD="$DOCKER_CMD -v $(pwd)/artifacts/app-config.test.yaml:/opt/app-root/src/app-config.test.yaml"
          fi
          DOCKER_CMD="$DOCKER_CMD -v $(pwd)/artifacts/dynamic-plugins.test.yaml:/opt/app-root/src/dynamic-plugins.yaml"
          
          # Add Docker config and environment variables
          echo "Using docker auth file: $HOME/.docker/config.json"
          DOCKER_CMD="$DOCKER_CMD -v $HOME/.docker/config.json:/root/.docker/config.json:ro"
          DOCKER_CMD="$DOCKER_CMD -e REGISTRY_AUTH_FILE=/root/.docker/config.json"
          DOCKER_CMD="$DOCKER_CMD -e SKIP_INTEGRITY_CHECK=true"
          
          # Add image and command
          DOCKER_CMD="$DOCKER_CMD --entrypoint /bin/bash quay.io/rhdh-community/rhdh:1.6 -c '"
          DOCKER_CMD="$DOCKER_CMD set -ex; "
          DOCKER_CMD="$DOCKER_CMD PLUGINS_ROOT=/opt/app-root/src/dynamic-plugins-root; "
          DOCKER_CMD="$DOCKER_CMD GENERATED_CONFIG=\$PLUGINS_ROOT/app-config.dynamic-plugins.yaml; "
          DOCKER_CMD="$DOCKER_CMD INSTALL_SCRIPT=/opt/app-root/src/install-dynamic-plugins.sh; "
          DOCKER_CMD="$DOCKER_CMD mkdir -p \$PLUGINS_ROOT; "
          DOCKER_CMD="$DOCKER_CMD \$INSTALL_SCRIPT \$PLUGINS_ROOT; "
          DOCKER_CMD="$DOCKER_CMD exec node packages/backend"
          
          # Add config files to command (optional)
          [ -f "./artifacts/app-config.yaml" ] && DOCKER_CMD="$DOCKER_CMD --config /opt/app-root/src/app-config.yaml"
          [ -f "./artifacts/app-config.test.yaml" ] && DOCKER_CMD="$DOCKER_CMD --config /opt/app-root/src/app-config.test.yaml"
          DOCKER_CMD="$DOCKER_CMD --config /opt/app-root/src/dynamic-plugins.yaml"
          DOCKER_CMD="$DOCKER_CMD --config \$GENERATED_CONFIG'"
          
          echo "Running: $DOCKER_CMD"
          eval "$DOCKER_CMD"

      - name: Wait for RHDH to be ready
        run: |
          set -e
          for i in $(seq 1 10); do
            if curl -fsS http://localhost:7007/health >/dev/null; then
              echo "RHDH is ready"; exit 0; fi
            echo "Waiting for RHDH... (Attempt ${i}/10)"
            # Check if container is still running
            if ! docker ps | grep -q rhdh; then
              echo "Container stopped unexpectedly."
              exit 1
            fi
            sleep 10
          done
          echo "RHDH did not become ready in time."
          exit 1

      - name: Check plugin installation folder structure
        run: docker exec rhdh ls -l /opt/app-root/src/dynamic-plugins-root

      - name: Check contents of app-config.dynamic-plugins.yaml
        run: docker exec rhdh cat /opt/app-root/src/dynamic-plugins-root/app-config.dynamic-plugins.yaml

      - name: Basic health check
        run: |
          curl -fsS http://localhost:7007/health

      - name: Verify plugin loading
        run: |
          set -e
          PLUGINS=$(grep -Eo '!([^[:space:]]+)' ./artifacts/dynamic-plugins.test.yaml | sed 's/^!//' | sort -u)
          if [ -z "$PLUGINS" ]; then
            echo "No plugins found in dynamic-plugins.test.yaml"; exit 1
          fi
          LOGS=$(docker logs rhdh || true)
          # Check each plugin appears as loaded in logs
          for plugin in $PLUGINS; do
            echo "Assertion loading of plugin: $plugin"
            echo "$LOGS" | grep -E "Loaded dynamic (frontend|backend) plugin.*${plugin}" >/dev/null || {
              echo "Missing 'Loaded dynamic plugin' log for ${plugin}"; exit 1; }
          done
          # Ensure no obvious loading errors are present
          if echo "$LOGS" | grep -E "(InstallException|Error while adding OCI plugin|Failed to load dynamic plugin|dynamic plugin.*error)" >/dev/null; then
            echo "Detected dynamic plugin loading errors in logs"; exit 1
          fi

      - name: Container logs
        if: always()
        run: docker logs rhdh || true

      - name: Cleanup
        if: always()
        run: docker rm -f rhdh || true


