name: Run Plugin Integration Tests

on:
  workflow_call:
    inputs:
      workspace-path:
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download dynamic-plugins test config
        uses: actions/download-artifact@v4
        with:
          name: dynamic-plugins-test
          path: ./artifacts

      - name: Download root app-config.yaml
        uses: actions/download-artifact@v4
        with:
          name: app-config-root
          path: ./artifacts

      - name: Download workspace app-config.test.yaml
        uses: actions/download-artifact@v4
        with:
          name: app-config-workspace
          path: ./artifacts

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Start RHDH with Layered Test Config
        env:
          WORKSPACE_PATH: ${{ inputs.workspace-path }}
        run: |
          set -euo pipefail
          echo "Workspace path: ${WORKSPACE_PATH}"
          ls -R ./artifacts || true
          docker run -d --name rhdh -p 7007:7007 \
            -v "$(pwd)/artifacts/workspaces/tests/app-config.yaml:/opt/app-root/src/app-config.yaml" \
            -v "$(pwd)/artifacts/${WORKSPACE_PATH}/tests/app-config.test.yaml:/opt/app-root/src/app-config.test.yaml" \
            -v "$(pwd)/artifacts/${WORKSPACE_PATH}/tests/dynamic-plugins.test.yaml:/opt/app-root/src/dynamic-plugins.yaml" \
            -v "$HOME/.docker/config.json:/root/.docker/config.json:ro" \
            -e "SKIP_INTEGRITY_CHECK=true" \
            --entrypoint "/bin/bash" \
            quay.io/rhdh-community/rhdh:1.6 \
            -c '

              set -ex
              PLUGINS_ROOT="/opt/app-root/src/dynamic-plugins-root"
              GENERATED_CONFIG="$PLUGINS_ROOT/app-config.dynamic-plugins.yaml"
              INSTALL_SCRIPT="/opt/app-root/src/install-dynamic-plugins.sh"

              mkdir -p "$PLUGINS_ROOT"
              "$INSTALL_SCRIPT" "$PLUGINS_ROOT"

              exec node packages/backend \
                --config /opt/app-root/src/app-config.yaml \
                --config /opt/app-root/src/app-config.test.yaml \
                --config /opt/app-root/src/dynamic-plugins.yaml \
                --config "$GENERATED_CONFIG"
            '

      - name: Wait for RHDH to be ready
        run: |
          set -e
          for i in $(seq 1 10); do
            if curl -fsS http://localhost:7007/health >/dev/null; then
              echo "RHDH is ready"; exit 0; fi
            echo "Waiting for RHDH... (Attempt ${i}/10)"
            sleep 10
          done
          echo "RHDH did not become ready in time"; exit 1

      - name: Check plugin installation folder structure
        run: docker exec rhdh ls -l /opt/app-root/src/dynamic-plugins-root

      - name: Check contents of app-config.dynamic-plugins.yaml
        run: docker exec rhdh cat /opt/app-root/src/dynamic-plugins-root/app-config.dynamic-plugins.yaml

      - name: Basic health check
        run: |
          curl -fsS http://localhost:7007/health

      - name: Container logs
        if: always()
        run: docker logs rhdh || true

      - name: Cleanup
        if: always()
        run: docker rm -f rhdh || true


